# Nombre del servicio/aplicación
service: tenpines-conf

# Creamos un paquete optimizado para las funciones
package:
  individually: true

plugins:
  - serverless-bundle # Empaquetamos las funciones utilizando webpack
  - serverless-offline # Offline nos permite invocar las funciones localmente, entre otras cosas.
  - serverless-dotenv-plugin # Load .env as environment variables (Mo lo utilizamos en este ejemplo)

provider:
  name: aws # El nombre del proovedor
  runtime: nodejs12.x # El lenguaje que utilizamos
  stage: dev # La stage por defecto
  region: us-east-1 # La región de aws

  # Las variable de ambiente
  environment:
    stage: ${self:provider.stage}
    tableName: ${ssm:${opt:stage}_TABLE_NAME}

   # Las policies para el rol que tendrán nuestras funciones
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:Query"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:Scan"
      Resource: "*"

# Las lambdas/funciones
functions:
  addQuote:
    handler: src/handlers/add.handler
    events:
      - http:
          path: add
          method: post
    getRandomQuote:
      handler: src/handlers/getRandom.handler
      events:
        - http:
            path: getRandom
            method: get

