version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
      - image: amazon/dynamodb-local

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - run: # test what branch we're on.
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}

      # run tests!
      - run:
          name: Run tests
          command: npm test --passWithNoTests

      - run:
          name: Deploy application
          command: |
            deployStage="review"
            if [ "${CIRCLE_BRANCH}" == "dev" ] || [ "${CIRCLE_BRANCH}" == "staging" ] || [ "${CIRCLE_BRANCH}" == "prod"  ]; then
              deployStage=${CIRCLE_BRANCH}
            fi
            sls deploy --stage ${deployStage}
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
